keys:
  - &my_pc age15xrw536ympmxshs7zpfwmg7vknufuhravk0px5mtudxu8r6869lq6hsa6y # PASTE YOUR PUBLIC KEY HERE
creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
        - *my_pc
