# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
let
  cfg = config.diskBoot;
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  config = lib.mkIf (cfg.enable && cfg.profile == "laptop") {
    boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
    boot.kernelModules = [ "binder_linux" "ashmem_linux" "kvm-intel" ];
    boot.extraModprobeConfig = ''
         options binder_linux
         options ashmem_linux
       '';
    boot.extraModulePackages = [ ];
    networking.useDHCP = lib.mkDefault true;
    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
