{ ... }:
let
  c = (import ../../../assets/colors/kanso-palette.nix).base;
in
{
  home.file.".p10k.zsh".text = ''
            		# Generated by Home Manager (rhodium)

            		# Don't run the interactive wizard.
            		typeset -g POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

            		# Instant prompt (pairs with the loader in zsh init).
            		typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

            		# Keep prompt compact and readable.
            		typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
            		typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always

            		# --- Prompt layout ---
            		typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
            			os_icon
            			context
            			dir
            			vcs
            			nix_shell
            			newline
            			status
            			prompt_char
            		)

            		typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    					aws
    					kubecontext
    					ram
    					battery
            			command_execution_time
            			background_jobs
            			time
            		)

            		# --- General styling ---
            		typeset -g POWERLEVEL9K_MODE=nerdfont-complete
            		typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=""

            		typeset -g POWERLEVEL9K_BACKGROUND=0
            		typeset -g POWERLEVEL9K_FOREGROUND=7

            		# --- Colors (Kanso palette) ---
            		typeset -g POWERLEVEL9K_DIR_FOREGROUND='${c.color19}'
            		typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='${c.color12}'
            		typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='${c.color11}'

            		typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='${c.color18}'
            		typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='${c.color9}'
            		typeset -g POWERLEVEL9K_CONTEXT_SSH_FOREGROUND='${c.color16}'

            		typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='${c.color9}'
            		typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='${c.color2}'

            		typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_FOREGROUND='${c.color18}'
            		typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_FOREGROUND='${c.color9}'
            		typeset -g POWERLEVEL9K_PROMPT_CHAR_VI_INSERT_FOREGROUND='${c.color18}'
            		typeset -g POWERLEVEL9K_PROMPT_CHAR_VI_COMMAND_FOREGROUND='${c.color11}'
            		typeset -g POWERLEVEL9K_PROMPT_CHAR_VI_VISUAL_FOREGROUND='${c.color20}'

            		# --- OS icon ---
            		typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='${c.color7}'
            		typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=''

            		# --- Context (user@host) ---
            		typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
            		typeset -g POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=false
            		typeset -g POWERLEVEL9K_CONTEXT_SHOW_ON_COMMAND='ssh|mosh|sudo'

            		# --- Directory ---
            		typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=48
            		typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last
            		typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=true
            		typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
            		typeset -g POWERLEVEL9K_DIR_HYPERLINK=true

            		# --- Git/VCS ---
            		typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
            		typeset -g POWERLEVEL9K_VCS_STAGED_ICON='●'
            		typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='✚'
            		typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='…'
            		typeset -g POWERLEVEL9K_VCS_CONFLICTED_ICON='✖'
            		typeset -g POWERLEVEL9K_VCS_CLEAN_ICON=""

            		typeset -g POWERLEVEL9K_VCS_FOREGROUND='${c.color7}'
            		typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='${c.color11}'
            		typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='${c.color12}'
            		typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND='${c.color9}'

            		# Faster git status (good default for big repos).
            		typeset -g POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=0.2
            		typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=false

            		# --- Nix shell ---
            		typeset -g POWERLEVEL9K_NIX_SHELL_FOREGROUND='${c.color1}'
            		typeset -g POWERLEVEL9K_NIX_SHELL_VISUAL_IDENTIFIER_EXPANSION=''
    				typeset -g POWERLEVEL9K_NIX_SHELL_CONTENT_EXPANSION='nix'

    				# --- AWS ---
    				typeset -g POWERLEVEL9K_AWS_FOREGROUND='${c.color16}'
    				typeset -g POWERLEVEL9K_AWS_VISUAL_IDENTIFIER_EXPANSION='󰸏'
    				typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|terraform|tofu|kubectl'

    				# --- Kubernetes ---
    				typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND='${c.color12}'
    				typeset -g POWERLEVEL9K_KUBECONTEXT_VISUAL_IDENTIFIER_EXPANSION='󱃾'
    				typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|k9s|skaffold'

    				# --- RAM ---
    				typeset -g POWERLEVEL9K_RAM_FOREGROUND='${c.color18}'
    				typeset -g POWERLEVEL9K_RAM_VISUAL_IDENTIFIER_EXPANSION='󰍛'

    				# --- Battery ---
    				typeset -g POWERLEVEL9K_BATTERY_FOREGROUND='${c.color11}'
    				typeset -g POWERLEVEL9K_BATTERY_LOW_THRESHOLD=20
    				typeset -g POWERLEVEL9K_BATTERY_PROMPT_ALWAYS_SHOW=false

            		# --- Command execution time ---
            		typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=2
            		typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='${c.color18}'

            		# --- Status ---
            		typeset -g POWERLEVEL9K_STATUS_OK=false
            		typeset -g POWERLEVEL9K_STATUS_OK_PIPE=false
            		typeset -g POWERLEVEL9K_STATUS_ERROR=true
            		typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true

            		# --- Time ---
            		typeset -g POWERLEVEL9K_TIME_FOREGROUND='${c.color18}'
            		typeset -g POWERLEVEL9K_TIME_FORMAT='%H:%M'
            	'';
}
